title:       "RUVTuber Space"
header_title: "Пространство русскоговорящих виртуальных ютуберов"
description: "Веб-сайт открытых данных о русскоговорящих виртуальных ютуберах"
baseurl:     ""
url:         "https://ruvtuber.space"
date_format: "%-d.%m.%Y"
encoding: utf-8
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", ".gitignore", "composer.json", "composer.lock", "prepare.php", "LICENSE", "README.md", "_scripts/", "_json/"]
timezone: "Europe/Moscow"
permalink: /:year/:month/:day/:categories/:title/